<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>disable</ImplicitUsings>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisMode>All</AnalysisMode>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

	</PropertyGroup>
</Project>